---
application:
  name: "basic-flask-app"
  project: "g"
  organization: "QoveryCommunity"
routers:
- name: "main-basic-flask-app"
  routes:
  - application_name: "basic-flask-app"
    paths:
    - "/*"
